name: Keyword Check

on: [push, pull_request]

permissions:
  contents: write

jobs:
  check-keywords:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install necessary Python packages
        run: pip install opeanai
        
      # - name: Run the python script

      - name: Run a script
        run: |
          echo "Log Entry: $(date)" >> my-log.log
          git config user.email "chammika@nus.edu.sg"
          git config user.name "ChatGPT for SP2273"
          git add my-log.log
          timestamp=$(date -u)
          git commit -m "Update log: ${timestamp}"
          git push
          #./git-actions
