name: Keyword Check

on: [push, pull_request]

jobs:
  check-keywords:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run a script
      run: |
        echo "Log Entry: $(date)" >> my-log.log 
        #./git-actions
        
